CREATE TABLE IF NOT EXISTS app_configs (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

INSERT OR IGNORE INTO app_configs (key, value) VALUES
('start', '👋 Chào mừng bạn đến shop! Nhấn nút bên dưới để khám phá sản phẩm ngay.'),
('help', '❓ Cách dùng:\n• /shop xem sản phẩm\n• /orders xem đơn\n• /help xem trợ giúp.\n💬 Hỗ trợ: trả lời tin nhắn này.'),
('fallback_qty', '🔢 Hãy nhập số lượng (1..999) hoặc chọn nhanh bằng nút.'),
('fallback_plan', '📅 Chọn gói/tháng bằng các nút bên dưới để tiếp tục.'),
('fallback_info', '📝 Nhập thông tin kích hoạt (ví dụ: email) để hoàn tất.'),
('fallback_default', '👉 Dùng /shop để xem sản phẩm hoặc /help để xem trợ giúp.'),
('callback_ack', '✅ Đã nhận thao tác'),
('help_inline', 'Hướng dẫn: /shop để xem sản phẩm, chọn sản phẩm → nhập số lượng → chuyển khoản đúng memo để nhận file. /orders để xem đơn của bạn.'),
('plan_invalid_for_product', 'Gói không hợp lệ cho sản phẩm này.'),
('plan_chosen', 'Đã chọn gói: {label} ({price}đ)\n📝 {prompt}'),
('plan_not_found', 'Gói không tồn tại.'),
('user_unknown', 'Không xác định user.'),
('user_unknown_retry', 'Không xác định user, thử lại sau.'),
('order_not_found', 'Không tìm thấy đơn.'),
('cancel_not_owner', 'Bạn không thể huỷ đơn này.'),
('cancel_already_paid', 'Đơn đã thanh toán, không thể huỷ.'),
('order_cancelled', 'Đơn đã được huỷ.'),
('action_invalid', 'Hành động không hợp lệ, vui lòng thử lại.'),
('qty_invalid', 'Số lượng không hợp lệ, nhập 1..999.'),
('product_not_found', 'Sản phẩm không tồn tại.'),
('info_prompt', '📝 {prompt}\n\nVui lòng nhập chính xác để xử lý đơn.'),
('info_empty', 'Thông tin không được để trống, vui lòng nhập lại (ví dụ: email).'),
('info_too_long', 'Thông tin quá dài (tối đa 200 ký tự).'),
('no_products', 'Hiện chưa có sản phẩm.'),
('no_orders', 'Bạn chưa có đơn nào.'),
('stock_out', 'Kho hiện hết hàng, vui lòng chọn sản phẩm khác.'),
('stock_not_enough', 'Kho chỉ còn {stock} sản phẩm, bạn đã chọn {qty}. Vui lòng nhập lại số lượng.'),
('hm_order_free', '✅ Key miễn phí: {key}'),
('hm_order_pending', '📋 Đơn {plan} ({billing})\n👤 {name}\n💰 Chuyển khoản nội dung: {code}'),
('hm_confirm_success', '✅ Thanh toán thành công!\n🔑 Key: {key}\n📦 Gói: {plan}\n\nNhập key vào app HiveMind để sử dụng.'),
('hm_api_error', '❌ Không thể kết nối server. Vui lòng thử lại sau.'),
('hm_decode_error', '❌ Link không hợp lệ. Vui lòng thử lại từ website.'),
('hm_not_configured', '⚠️ Tính năng HiveMind chưa được cấu hình.');
